// Mock data for NESAA ecommerce platform

export const categories = [
  {
    id: 1,
    name: "Bags",
    slug: "bags",
    description: "Handcrafted leather bags for everyday",
    image: "/category-bags.png",
  },
  {
    id: 2,
    name: "Belts",
    slug: "belts",
    description: "Premium leather belts ",
    image: "/category-belts.png",
  },
  {
    id: 3,
    name: "Wallets",
    slug: "wallets",
    description: "Elegant leather wallets designed to last",
    image: "/category-wallets.png",
  },
  {
    id: 4,
    name: "Accessories",
    slug: "accessories",
    description: "Curated leather accessories and more",
    image: "/category-accessories.png",
  },
];

export const products = [
  {
    id: 1,
    name: "Classic Leather Tote",
    slug: "classic-leather-tote",
    category: "bags",
    description:
      "A timeless leather tote perfect for daily use. Handcrafted from premium vegetable-tanned leather.",
    images: [
      "/leatherTote.png",
      "/images/product-1-detail.jpg",
      "/images/product-1-back.jpg",
    ],
    single: {
      price: 285,
      moq: 1,
    },
    wholesale: {
      price: 165,
      moq: 5,
    },
    rating: 4.8,
    reviews: 34,
    inStock: true,
    colors: ["Natural", "Chocolate", "Black"],
    materials: "Premium Vegetable-Tanned Leather",
    dimensions: 'W: 14" H: 11" D: 5"',
  },
  {
    id: 2,
    name: "Structured Crossbody Bag",
    slug: "structured-crossbody-bag",
    category: "bags",
    description:
      "Elegantly designed crossbody bag with adjustable strap. Perfect for everyday wear.",
    images: [
      "/crossbody.webp",
      "/images/product-2-detail.jpg",
      "/images/product-2-strap.jpg",
    ],
    single: {
      price: 245,
      moq: 1,
    },
    wholesale: {
      price: 145,
      moq: 5,
    },
    rating: 4.7,
    reviews: 28,
    inStock: true,
    colors: ["Natural", "Burgundy", "Navy"],
    materials: "Full-Grain Leather",
    dimensions: 'W: 10" H: 8" D: 3"',
  },
  {
    id: 3,
    name: "Italian Leather Belt",
    slug: "italian-leather-belt",
    category: "belts",
    description:
      "Premium Italian leather belt with solid brass buckle. Timeless elegance.",
    images: [
      "/italian.png",
      "/images/product-3-buckle.jpg",
      "/images/product-3-wear.jpg",
    ],
    single: {
      price: 95,
      moq: 1,
    },
    wholesale: {
      price: 55,
      moq: 10,
    },
    rating: 4.9,
    reviews: 52,
    inStock: true,
    colors: ["Black", "Brown", "Tan"],
    materials: "Full-Grain Italian Leather",
    dimensions: "Available in S, M, L, XL",
  },
  {
    id: 4,
    name: "Minimalist Leather Wallet",
    slug: "minimalist-leather-wallet",
    category: "wallets",
    description:
      "Sleek minimalist wallet designed to hold essentials. Card slots for organization.",
    images: [
      "/wallet.png",
      "/images/product-4-open.jpg",
      "/images/product-4-detail.jpg",
    ],
    single: {
      price: 125,
      moq: 1,
    },
    wholesale: {
      price: 65,
      moq: 8,
    },
    rating: 4.6,
    reviews: 19,
    inStock: true,
    colors: ["Black", "Natural", "Cognac"],
    materials: "Vegetable-Tanned Leather",
    dimensions: 'W: 4.5" H: 3.5"',
  },
  {
    id: 5,
    name: "Bifold Leather Wallet",
    slug: "bifold-leather-wallet",
    category: "wallets",
    description:
      "Classic bifold wallet with multiple card slots. Durable and stylish.",
    images: [
      "/images/product-5-main.jpg",
      "/images/product-5-open.jpg",
      "/images/product-5-wear.jpg",
    ],
    single: {
      price: 145,
      moq: 1,
    },
    wholesale: {
      price: 75,
      moq: 8,
    },
    rating: 4.7,
    reviews: 31,
    inStock: true,
    colors: ["Black", "Brown", "Oxblood"],
    materials: "Premium Leather",
    dimensions: 'W: 3.75" H: 4.5"',
  },
  {
    id: 6,
    name: "Leather Keychain Set",
    slug: "leather-keychain-set",
    category: "accessories",
    description:
      "Set of 3 premium leather keychains. Personalization available.",
    images: [
      "/images/product-6-main.jpg",
      "/images/product-6-detail.jpg",
      "/images/product-6-set.jpg",
    ],
    single: {
      price: 45,
      moq: 1,
    },
    wholesale: {
      price: 20,
      moq: 15,
    },
    rating: 4.8,
    reviews: 45,
    inStock: true,
    colors: ["Natural", "Black", "Tan"],
    materials: "Vegetable-Tanned Leather",
    dimensions: "Assorted sizes",
  },
];

export const users = [
  {
    id: 1,
    email: "customer@example.com",
    name: "John Doe",
    role: "customer",
    addresses: [
      {
        id: 1,
        type: "billing",
        name: "Home",
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
        country: "USA",
        isDefault: true,
      },
    ],
  },
  {
    id: 2,
    email: "admin@nesaa.com",
    name: "Admin User",
    role: "admin",
  },
];

export const orders = [
  {
    id: "ORDER-001",
    userId: 1,
    items: [
      {
        productId: 1,
        name: "Classic Leather Tote",
        quantity: 1,
        pricing: "single",
        price: 285,
        color: "Natural",
      },
      {
        productId: 4,
        name: "Minimalist Leather Wallet",
        quantity: 2,
        pricing: "single",
        price: 125,
        color: "Black",
      },
    ],
    total: 535,
    status: "delivered",
    createdAt: new Date("2024-12-15"),
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "USA",
    },
  },
  {
    id: "ORDER-002",
    userId: 1,
    items: [
      {
        productId: 3,
        name: "Italian Leather Belt",
        quantity: 1,
        pricing: "single",
        price: 95,
        color: "Brown",
      },
    ],
    total: 95,
    status: "processing",
    createdAt: new Date("2024-12-20"),
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "USA",
    },
  },
];

export const translations = {
  en: {
    nav: {
      home: "Home",
      b2b: "B2B",
      shop: "Shop",
      about: "About",
      contact: "Contact",
      donate: "Donate",
      account: "Account",
      admin: "Admin",
      cart: "Cart",
      logout: "Logout",
      language: "Language",
    },
    hero: {
      title: "Premium Sustainable Leather",
      subtitle: "Handcrafted excellence for the discerning",
      cta: "Shop Now",
    },
    shop: {
      title: "Our Collection",
      filter: "Filters",
      sort: "Sort By",
      price: "Price: Low to High",
      rating: "Rating: High to Low",
      newest: "Newest First",
      allCategories: "All Categories",
    },
    product: {
      singlePrice: "Single Purchase",
      wholesalePrice: "Wholesale",
      moq: "Minimum Order:",
      quantity: "Quantity",
      addToCart: "Add to Cart",
      quickView: "Quick View",
      details: "Product Details",
      reviews: "Reviews",
      rating: "Rating",
      inStock: "In Stock",
      outOfStock: "Out of Stock",
    },
    cart: {
      title: "Shopping Cart",
      empty: "Your cart is empty",
      subtotal: "Subtotal",
      shipping: "Shipping",
      tax: "Tax",
      total: "Total",
      checkout: "Proceed to Checkout",
      continueShopping: "Continue Shopping",
      remove: "Remove",
      updateCart: "Update Cart",
    },
    checkout: {
      title: "Checkout",
      step1: "Shipping",
      step2: "Payment",
      step3: "Confirmation",
      shipping: "Shipping Address",
      payment: "Payment Method",
      placeOrder: "Place Order",
      orderConfirmed: "Order Confirmed",
      orderNumber: "Order Number",
    },
    account: {
      title: "My Account",
      profile: "Profile",
      addresses: "Addresses",
      orders: "Order History",
      settings: "Settings",
      logout: "Logout",
      editProfile: "Edit Profile",
      addAddress: "Add Address",
      viewOrder: "View Order",
    },
    donations: {
      title: "Give Back",
      description:
        "Support sustainable practices and environmental initiatives",
      makedonation: "Make a Donation",
      impact: "Your Impact",
    },
    contact: {
      title: "Get in Touch",
      email: "Email",
      phone: "Phone",
      message: "Message",
      send: "Send Message",
      address: "Address",
    },
    admin: {
      title: "Admin Dashboard",
      overview: "Overview",
      orders: "Orders",
      products: "Products",
      customers: "Customers",
      settings: "Settings",
      totalOrders: "Total Orders",
      totalRevenue: "Total Revenue",
      totalCustomers: "Total Customers",
    },
  },
  nl: {
    nav: {
      home: "Startpagina",
      b2b: "B2B",
      shop: "Winkel",
      about: "Over ons",
      contact: "Contact",
      donate: "Donatie",
      account: "Mijn Account",
      admin: "Beheer",
      cart: "Winkelwagen",
      logout: "Afmelden",
      language: "Taal",
    },
    hero: {
      title: "Premium Duurzaam Leder",
      subtitle: "Ambachtelijk vakwerk voor de kieuwkeurige",
      cta: "Nu Winkelen",
    },
    shop: {
      title: "Onze Collectie",
      filter: "Filters",
      sort: "Sorteer op",
      price: "Prijs: Laag naar Hoog",
      rating: "Beoordeling: Hoog naar Laag",
      newest: "Nieuwste Eerst",
      allCategories: "Alle Categorieën",
    },
    product: {
      singlePrice: "Enkelvoudige Aankoop",
      wholesalePrice: "Groothandel",
      moq: "Minimum Bestelling:",
      quantity: "Hoeveelheid",
      addToCart: "Aan Winkelwagen",
      quickView: "Snelle Weergave",
      details: "Productdetails",
      reviews: "Beoordelingen",
      rating: "Beoordeling",
      inStock: "Op Voorraad",
      outOfStock: "Uitverkocht",
    },
    cart: {
      title: "Winkelwagen",
      empty: "Uw winkelwagen is leeg",
      subtotal: "Subtotaal",
      shipping: "Verzending",
      tax: "Belasting",
      total: "Totaal",
      checkout: "Doorgaan met Afrekenen",
      continueShopping: "Doorgaan met Winkelen",
      remove: "Verwijderen",
      updateCart: "Winkelwagen Bijwerken",
    },
    checkout: {
      title: "Afrekenen",
      step1: "Verzending",
      step2: "Betaling",
      step3: "Bevestiging",
      shipping: "Verzendadres",
      payment: "Betalingsmethode",
      placeOrder: "Bestelling Plaatsen",
      orderConfirmed: "Bestelling Bevestigd",
      orderNumber: "Bestelnum",
    },
    account: {
      title: "Mijn Account",
      profile: "Profiel",
      addresses: "Adressen",
      orders: "Ordergeschiedenis",
      settings: "Instellingen",
      logout: "Afmelden",
      editProfile: "Profiel Bewerken",
      addAddress: "Adres Toevoegen",
      viewOrder: "Bestelling Bekijken",
    },
    donations: {
      title: "Geven",
      description: "Ondersteu duurzame praktijken en milieuinitiatieven",
      makedonation: "Donatie Doen",
      impact: "Uw Impact",
    },
    contact: {
      title: "Neem Contact Op",
      email: "E-mailadres",
      phone: "Telefoon",
      message: "Bericht",
      send: "Bericht Verzenden",
      address: "Adres",
    },
    admin: {
      title: "Beheerdashboard",
      overview: "Overzicht",
      orders: "Bestellingen",
      products: "Producten",
      customers: "Klanten",
      settings: "Instellingen",
      totalOrders: "Totale Bestellingen",
      totalRevenue: "Totale Inkomsten",
      totalCustomers: "Totale Klanten",
    },
  },
};

export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    title: "Fashion Entrepreneur",
    content:
      "The quality and craftsmanship of NESAA products is unmatched. Highly recommend.",
    rating: 5,
    avatar: "/images/testimonial-1.jpg",
  },
  {
    id: 2,
    name: "Michael Chen",
    title: "Executive",
    content:
      "Premium leather goods that last. Invested in 3 bags and love them all.",
    rating: 5,
    avatar: "/images/testimonial-2.jpg",
  },
  {
    id: 3,
    name: "Emma Rodriguez",
    title: "Sustainability Advocate",
    content:
      "Finally found ethical and luxury goods in one place. NESAA is the way to go.",
    rating: 5,
    avatar: "/images/testimonial-3.jpg",
  },
];

export const donationTiers = [
  {
    id: 1,
    name: "Supporter",
    amount: 25,
    description: "Help us support 1 person",
    color: "green",
  },
  {
    id: 2,
    name: "Champion",
    amount: 50,
    description: "Support sustainable initiatives",
    color: "emerald",
  },
  {
    id: 3,
    name: "Visionary",
    amount: 100,
    description: "Fund a full project",
    color: "teal",
  },
];
